name: AWS Nuke Execution

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install ekristen/aws-nuke
        run: |
          # Fetch and install the latest release binary for Linux x86_64
          curl -s https://api.github.com/repos/ekristen/aws-nuke/releases/latest \
          | grep "browser_download_url.*linux-amd64.tar.gz" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi -
          
          tar -xzf aws-nuke-*-linux-amd64.tar.gz
          sudo mv aws-nuke /usr/local/bin/aws-nuke
          aws-nuke version

      - name: Execute AWS Nuke (Dry Run)
        run: |
          aws-nuke run \
            --config=nuke-config.yml \
            --no-prompt

            
    #   - name: Execute AWS Nuke (REAL DELETION)
    #     run: |
    #       aws-nuke run \
    #         --config nuke-config.yml \
    #         --no-prompt \
    #         --no-dry-run